server:
 port: 8070
 context-path: /v/springboot
 
 
test: 
 yml: @project.name@
 delimeter: ${spring.learning.name}
 version1: v1.0
 
secret: 
 token: djtddjeklewr34k5j489dsidjlkjdkejkj3344